### PR TITLE
fix pathwayDB_nodes

### PR DESCRIPTION
**Pull request by egeulgen**
I just updated the pathway lists in `pathwayDB_nodes` so that they all contain pathways obtained via `graphite::pathways()` and the method works properly.

### CODE REVIEW

**Comment by egeulgen** [comment]
I only updated "reactome" (which still gives an error for some reason) and "kegg" (which seems to work fine), "nci" still needs to get updated

**Comment by egeulgen** [comment]
I updated all `pathwayDB_nodes` via `graphite` (all of "reactome", "kegg" and "nci"). Should work properly now

**Comment by galdinstag** [comment]
Hey Ege!
Thanks a lot for your contribution and for your effort on this bug. I highly appreciate it.
I actually noticed it just last week and i am fixing it in the code itself. In the RData you provided i see that there are 159 pathways in pathwayDB_nodes[["reactome"]] that are not contained in the graphite package, did you notice it?
I will update the code as soon as i test that its all good.
Thanks again,
Gal

**Comment by egeulgen** [comment]
Hey Gal,
I did notice that but it seems weird because I used graphite to create pathwayDB_nodes.
I'll just wait for your update :)
thank you for this great tool!
Best,
-E

**Pull request closed without merging**
